### ISSUE TITLE
Could not able to Fetch the Watchable Library from jcenter

### ISSUE THREAD

**Issue by WIPKarthik** [gladed/watchable#100]
We could not able to fetch the dependency `io.gladed:watchable:0.6.22` from jcenter. From last two days we were facing this issue and now from today morning we can able to fetch from the jcenter repo.

https://jfrog.com/blog/jcenter-sunset/ As we see here that the Final shutdown is on August 15th i would request you to resolve this.

@GladeDiviney

**Comment by GladeDiviney** [comment]
Thanks for letting me know about this! And sorry for the inconvenience.

I recommend jitpack as a replacement:

```gradle
repositories {
    // ...
    maven { url 'https://www.jitpack.io' }
}

dependencies {
    implementation 'com.github.gladed:watchable:v0.6.21'
}
```

**Comment by WIPKarthik** [comment]
@GladeDiviney Could you check once, Could not resolve com.github.gladed:watchable:v0.6.21.

Look like the build is failed https://github.com/gladed/watchable/pull/101

**Comment by GladeDiviney** [comment]
Hi @WIPKarthik, the suggestion above is to use jitpack.io. I confirmed this was a working solution in a separate sample project.

If jitpack does not work, consider including a binary form of this library in your own builds as a static artifact.

Builds for #101 are failing for an unrelated reason having to do with CircleCI.

You're quite welcome to submit PRs that would help improve things!
